Making sure that Unity Unit Tests that don't pass make the build fail; (#205)
* this is designed to fail;

* Testing to see if we can get Windows to fail;

* Now let's see if Ubuntu fails;

* Oops. NOW we can see if Ubuntu fails;

* And now let's make sure Windows and Ubuntu pass;

* Ubuntu & Windows should FAIL;

* Ubuntu & Windows should PASS;

diff --git a/.github/workflows/ubuntu.yml b/.github/workflows/ubuntu.yml
--- a/.github/workflows/ubuntu.yml
+++ b/.github/workflows/ubuntu.yml
@@ -4,7 +4,7 @@ on:
   push:
     branches:
       - master
-      # - dev/*
+      - dev/*
     paths:
       - .github/workflows/ubuntu.yml
       - Assets/**
@@ -95,6 +95,13 @@ jobs:
         with:
           name: unity-test-results-${{ github.sha }}
           path: artifacts
+
+      - name: Fail if any Unity test failed
+        run: |
+          if grep -R 'result="Failed"' artifacts/*-results.xml; then
+            echo "Unity tests failed."
+            exit 1
+          fi
 
       - name: Debug git status (optional)
         run: |
